In [ ]:
import pandas as pd
df=pd.read_csv('/content/Employee.csv')
df

,employee_id,name,department,age,salary,city,gender,designation,experience_years
0,10001,Priya Verma,Sales,35,126156.0,Jaipur,Male,Data Scientist,5.0
1,10002,Sai Patel,Marketing,46,38822.0,Bengaluru,Female,Data Scientist,2.0
2,10003,Arjun Singh,R&D,56,110928.0,Hyderabad,Male,Data Scientist,5.0
3,10004,Neha Verma,Finance,56,71586.0,Chandigarh,Male,Software Engineer,0.0
4,10005,Priya Verma,R&D,52,47764.0,Delhi,Female,Analyst,17.0
...,...,...,...,...,...,...,...,...,...
3495,13496,Priya Verma,IT,24,31066.0,Chandigarh,Female,Data Scientist,8.0
3496,13497,Sai Gupta,Support,21,48646.0,Mumbai,Male,Manager,18.0
3497,13498,Priya Mehta,HR,31,149886.0,Mumbai,Male,Manager,18.0
3498,13499,Vivaan Singh,HR,28,40735.0,Pune,Male,Manager,1.0
3499,13500,Kavya Mehta,Support,45,141726.0,Mumbai,Male,NaN,20.0

In [ ]:
df.to_excel('emp.xlsx', index=False)

In [ ]:
df[df['age']> 40]

,employee_id,name,department,age,salary,city,gender,designation,experience_years
1,10002,Sai Patel,Marketing,46,38822.0,Bengaluru,Female,Data Scientist,2.0
2,10003,Arjun Singh,R&D,56,110928.0,Hyderabad,Male,Data Scientist,5.0
3,10004,Neha Verma,Finance,56,71586.0,Chandigarh,Male,Software Engineer,0.0
4,10005,Priya Verma,R&D,52,47764.0,Delhi,Female,Analyst,17.0
12,10013,Sneha Gupta,Sales,51,36823.0,Bengaluru,Female,Data Scientist,20.0
...,...,...,...,...,...,...,...,...,...
3490,13491,Ira Singh,Sales,47,103446.0,Bengaluru,Female,Data Scientist,16.0
3491,13492,Reyansh Patel,Finance,54,72292.0,Bengaluru,Female,HR Executive,4.0
3492,13493,Ananya Mehta,Marketing,41,129406.0,Mumbai,Female,Data Scientist,0.0
3494,13495,Pooja Gupta,Support,42,36019.0,Kolkata,Female,Analyst,6.0
3499,13500,Kavya Mehta,Support,45,141726.0,Mumbai,Male,NaN,20.0

In [ ]:
df.sort_values(by='salary', ascending=False)

,employee_id,name,department,age,salary,city,gender,designation,experience_years
1142,11143,Aanya Mehta,HR,60,149997.0,Chennai,Male,Data Scientist,6.0
2896,12897,Aditya Patel,Operations,50,149992.0,Chennai,Female,Team Lead,19.0
3497,13498,Priya Mehta,HR,31,149886.0,Mumbai,Male,Manager,18.0
914,10915,Ananya Singh,Sales,47,149796.0,Chennai,Female,Software Engineer,3.0
3292,13293,Ananya Singh,Finance,39,149736.0,Hyderabad,Female,Software Engineer,3.0
...,...,...,...,...,...,...,...,...,...
3372,13373,Sneha Sharma,Support,26,NaN,Chennai,Female,Analyst,0.0
3422,13423,Priya Patel,Support,30,NaN,Delhi,Male,Software Engineer,1.0
3423,13424,Diya Singh,IT,23,NaN,Delhi,Female,Software Engineer,2.0
3471,13472,Krishna Gupta,Marketing,52,NaN,Hyderabad,Female,Software Engineer,17.0
3484,13485,Sneha Patel,Finance,39,NaN,Delhi,Male,Data Scientist,3.0

In [ ]:
df.sort_values(by=["salary", "name"], ascending=[False, True])

,employee_id,name,department,age,salary,city,gender,designation,experience_years
1142,11143,Aanya Mehta,HR,60,149997.0,Chennai,Male,Data Scientist,6.0
2896,12897,Aditya Patel,Operations,50,149992.0,Chennai,Female,Team Lead,19.0
3497,13498,Priya Mehta,HR,31,149886.0,Mumbai,Male,Manager,18.0
914,10915,Ananya Singh,Sales,47,149796.0,Chennai,Female,Software Engineer,3.0
3292,13293,Ananya Singh,Finance,39,149736.0,Hyderabad,Female,Software Engineer,3.0
...,...,...,...,...,...,...,...,...,...
1536,11537,Vivaan Patel,R&D,48,NaN,Chandigarh,Female,Manager,16.0
1521,11522,Vivaan Singh,Finance,53,NaN,Hyderabad,Male,Software Engineer,6.0
2797,12798,Vivaan Singh,Finance,44,NaN,Delhi,Female,HR Executive,13.0
3079,13080,Vivaan Singh,Sales,49,NaN,Hyderabad,Female,HR Executive,6.0
1080,11081,Vivaan Verma,Support,46,NaN,Hyderabad,Female,Team Lead,19.0

In [ ]:
df.groupby('department').count()

,employee_id,name,age,salary,city,gender,designation,experience_years
department,,,,,,,,
Finance,435,435,435,415,410,435,416,407
HR,464,464,464,433,439,464,439,442
IT,412,412,412,389,385,412,392,386
Marketing,445,445,445,424,429,445,425,420
Operations,444,444,444,421,419,444,420,424
R&D,432,432,432,416,408,432,405,413
Sales,443,443,443,423,424,443,423,422
Support,425,425,425,404,411,425,405,411

In [ ]:
df.head(50)

,employee_id,name,department,age,salary,city,gender,designation,experience_years
0,10001,Priya Verma,Sales,35,126156.0,Jaipur,Male,Data Scientist,5.0
1,10002,Sai Patel,Marketing,46,38822.0,Bengaluru,Female,Data Scientist,2.0
2,10003,Arjun Singh,R&D,56,110928.0,Hyderabad,Male,Data Scientist,5.0
3,10004,Neha Verma,Finance,56,71586.0,Chandigarh,Male,Software Engineer,0.0
4,10005,Priya Verma,R&D,52,47764.0,Delhi,Female,Analyst,17.0
5,10006,Krishna Sharma,HR,34,31674.0,Pune,Female,Data Scientist,1.0
6,10007,Krishna Kumar,Finance,22,146708.0,NaN,Female,Analyst,5.0
7,10008,Diya Singh,Marketing,33,34683.0,Mumbai,Female,Software Engineer,2.0
8,10009,Vihaan Verma,R&D,38,89494.0,Ahmedabad,Male,Data Scientist,3.0
9,10010,Sneha Kumar,Sales,21,56660.0,Kolkata,Male,Team Lead,9.0
10,10011,Ishaan Singh,IT,31,81591.0,Ahmedabad,Female,Manager,1.0
11,10012,Muhammad Singh,IT,23,34290.0,Delhi,Male,Analyst,2.0
12,10013,Sneha Gupta,Sales,51,36823.0,Bengaluru,Female,Data Scientist,20.0
13,10014,Vihaan Singh,Marketing,49,48080.0,Chennai,Female,Analyst,NaN
14,10015,Kavya Patel,R&D,47,133622.0,Chennai,Female,NaN,NaN
15,10016,Priya Singh,IT,47,49501.0,Chandigarh,Female,HR Executive,13.0
16,10017,Kavya Verma,Finance,27,53071.0,Chandigarh,Male,HR Executive,19.0
17,10018,Aarav Kumar,IT,25,101248.0,Mumbai,Female,Software Engineer,18.0
18,10019,Kavya Sharma,Marketing,35,105382.0,Pune,Female,Team Lead,8.0
19,10020,Priya Singh,Support,43,122056.0,Hyderabad,Male,Team Lead,17.0
20,10021,Pooja Verma,R&D,51,140148.0,Mumbai,Male,Team Lead,3.0
21,10022,Aarav Kumar,Marketing,21,64334.0,NaN,Female,HR Executive,NaN
22,10023,Muhammad Kumar,Operations,41,25813.0,Ahmedabad,Female,Team Lead,16.0
23,10024,Krishna Singh,IT,49,52023.0,Pune,Male,HR Executive,9.0
24,10025,Aanya Mehta,HR,25,30508.0,Hyderabad,Female,Manager,0.0
25,10026,Kavya Sharma,Marketing,31,109337.0,Bengaluru,Female,Analyst,14.0
26,10027,Ishaan Verma,R&D,25,82449.0,Jaipur,Male,Manager,8.0
27,10028,Vihaan Sharma,Marketing,51,88458.0,Delhi,Female,HR Executive,7.0
28,10029,Priya Kumar,Support,22,52766.0,Bengaluru,Female,Team Lead,17.0
29,10030,Ishaan Kumar,Finance,57,91465.0,Jaipur,Female,Manager,9.0
30,10031,Reyansh Patel,Finance,43,36604.0,Ahmedabad,Male,Analyst,7.0
31,10032,Aarav Singh,HR,22,98145.0,Chennai,Female,Manager,1.0
32,10033,Ishaan Verma,Operations,53,28178.0,NaN,Female,Software Engineer,5.0
33,10034,Diya Kumar,HR,36,104389.0,Hyderabad,Male,HR Executive,12.0
34,10035,Ishaan Verma,R&D,26,NaN,Chennai,Female,Software Engineer,12.0
35,10036,Riya Patel,R&D,52,79792.0,Pune,Male,HR Executive,3.0
36,10037,Aditya Kumar,Operations,53,137300.0,Kolkata,Male,Software Engineer,20.0
37,10038,Diya Singh,IT,25,51065.0,Mumbai,Female,HR Executive,4.0
38,10039,Aarav Kumar,IT,27,90544.0,Ahmedabad,Female,Data Scientist,17.0
39,10040,Priya Singh,Marketing,39,117011.0,Ahmedabad,Male,Data Scientist,NaN
40,10041,Aanya Singh,Operations,34,111114.0,Chennai,Female,Team Lead,6.0
41,10042,Ira Verma,IT,38,119920.0,Ahmedabad,Female,Analyst,6.0
42,10043,Priya Sharma,Sales,40,112129.0,NaN,Male,Data Scientist,3.0
43,10044,Sneha Singh,Support,37,35345.0,Delhi,Male,Manager,8.0
44,10045,Neha Sharma,HR,24,56057.0,Jaipur,Male,Manager,18.0
45,10046,Muhammad Patel,Finance,33,83751.0,Mumbai,Female,Analyst,NaN
46,10047,Ira Singh,Sales,25,54974.0,Pune,Male,Analyst,16.0
47,10048,Aditya Mehta,Sales,33,116755.0,Hyderabad,Female,Software Engineer,NaN
48,10049,Aarav Verma,R&D,45,129672.0,Kolkata,Female,HR Executive,14.0
49,10050,Vivaan Sharma,R&D,31,85836.0,Mumbai,Female,Software Engineer,2.0

In [ ]:
df.shape

(3500, 9)

In [ ]:
df.isnull()
df.isnull().sum()

employee_id           0
name                  0
department            0
age                   0
salary              175
city                175
gender                0
designation         175
experience_years    175
dtype: int64

In [ ]:
df.dropna()

,employee_id,name,department,age,salary,city,gender,designation,experience_years
0,10001,Priya Verma,Sales,35,126156.0,Jaipur,Male,Data Scientist,5.0
1,10002,Sai Patel,Marketing,46,38822.0,Bengaluru,Female,Data Scientist,2.0
2,10003,Arjun Singh,R&D,56,110928.0,Hyderabad,Male,Data Scientist,5.0
3,10004,Neha Verma,Finance,56,71586.0,Chandigarh,Male,Software Engineer,0.0
4,10005,Priya Verma,R&D,52,47764.0,Delhi,Female,Analyst,17.0
...,...,...,...,...,...,...,...,...,...
3494,13495,Pooja Gupta,Support,42,36019.0,Kolkata,Female,Analyst,6.0
3495,13496,Priya Verma,IT,24,31066.0,Chandigarh,Female,Data Scientist,8.0
3496,13497,Sai Gupta,Support,21,48646.0,Mumbai,Male,Manager,18.0
3497,13498,Priya Mehta,HR,31,149886.0,Mumbai,Male,Manager,18.0
3498,13499,Vivaan Singh,HR,28,40735.0,Pune,Male,Manager,1.0

In [ ]:
df.fillna({"salary": 1000000}, inplace=False)

,employee_id,name,department,age,salary,city,gender,designation,experience_years
0,10001,Priya Verma,Sales,35,126156.0,Jaipur,Male,Data Scientist,5.0
1,10002,Sai Patel,Marketing,46,38822.0,Bengaluru,Female,Data Scientist,2.0
2,10003,Arjun Singh,R&D,56,110928.0,Hyderabad,Male,Data Scientist,5.0
3,10004,Neha Verma,Finance,56,71586.0,Chandigarh,Male,Software Engineer,0.0
4,10005,Priya Verma,R&D,52,47764.0,Delhi,Female,Analyst,17.0
...,...,...,...,...,...,...,...,...,...
3495,13496,Priya Verma,IT,24,31066.0,Chandigarh,Female,Data Scientist,8.0
3496,13497,Sai Gupta,Support,21,48646.0,Mumbai,Male,Manager,18.0
3497,13498,Priya Mehta,HR,31,149886.0,Mumbai,Male,Manager,18.0
3498,13499,Vivaan Singh,HR,28,40735.0,Pune,Male,Manager,1.0
3499,13500,Kavya Mehta,Support,45,141726.0,Mumbai,Male,NaN,20.0

In [ ]:
df["name"]

0        Priya Verma
1          Sai Patel
2        Arjun Singh
3         Neha Verma
4        Priya Verma
            ...
3495     Priya Verma
3496       Sai Gupta
3497     Priya Mehta
3498    Vivaan Singh
3499     Kavya Mehta
Name: name, Length: 3500, dtype: object

In [ ]:
data = {
    "EmployeeID": [101, 102, 103, 104, 105],
    "Name": ["Amit", "Neha", "Rahul", "Priya", "Karan"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Age": [25, 30, 35, 28, 40],
    "Salary": [45000, 55000, 60000, 52000, None]
}

df1 = pd.DataFrame(data)

In [ ]:
df1.head(3)

   EmployeeID   Name Department  Age   Salary
0         101   Amit         IT   25  45000.0
1         102   Neha         HR   30  55000.0
2         103  Rahul         IT   35  60000.0

In [ ]:
df1["Salary"].mean()

np.float64(53000.0)

In [ ]:
df1[df1["Salary"] > 50000]

   EmployeeID   Name Department  Age   Salary
1         102   Neha         HR   30  55000.0
2         103  Rahul         IT   35  60000.0
3         104  Priya    Finance   28  52000.0

In [ ]:
df1.sort_values(by="Age")

   EmployeeID   Name Department  Age   Salary
0         101   Amit         IT   25  45000.0
3         104  Priya    Finance   28  52000.0
1         102   Neha         HR   30  55000.0
2         103  Rahul         IT   35  60000.0
4         105  Karan         HR   40      NaN

In [ ]:
df1.groupby("Department")["Salary"].sum()

Department
Finance     52000.0
HR          55000.0
IT         105000.0
Name: Salary, dtype: float64

In [ ]:
df1["Bonus"] = df1["Salary"] * 0.10
df1

   EmployeeID   Name Department  Age   Salary   Bonus
0         101   Amit         IT   25  45000.0  4500.0
1         102   Neha         HR   30  55000.0  5500.0
2         103  Rahul         IT   35  60000.0  6000.0
3         104  Priya    Finance   28  52000.0  5200.0
4         105  Karan         HR   40      NaN     NaN

In [ ]:
df1["Salary"] = df1["Salary"].fillna(df1["Salary"].mean())
df1

   EmployeeID   Name Department  Age   Salary   Bonus
0         101   Amit         IT   25  45000.0  4500.0
1         102   Neha         HR   30  55000.0  5500.0
2         103  Rahul         IT   35  60000.0  6000.0
3         104  Priya    Finance   28  52000.0  5200.0
4         105  Karan         HR   40  53000.0     NaN

In [ ]:
df1.rename(columns={"EmployeeID": "ID"}, inplace=True)
df1

    ID   Name Department  Age   Salary   Bonus
0  101   Amit         IT   25  45000.0  4500.0
1  102   Neha         HR   30  55000.0  5500.0
2  103  Rahul         IT   35  60000.0  6000.0
3  104  Priya    Finance   28  52000.0  5200.0
4  105  Karan         HR   40  53000.0     NaN