In [2]:
import pandas as pd
df=pd.read_csv('/content/employee_dataset.csv')
df.head(5)

,employee_id,name,department,age,salary,city,gender,designation,experience_years
0,1,Simran,IT,44,109723,Pune,Female,Manager,12
1,2,Priya,Marketing,35,119406,Bangalore,Male,Analyst,2
2,3,Simran,HR,50,37769,Chandigarh,Female,Analyst,19
3,4,Arjun,Marketing,37,26682,Delhi,Male,Manager,0
4,5,Karan,HR,34,44816,Delhi,Female,Team Lead,26

In [3]:
df.to_excel('emp.xlsx', index=False)

In [4]:
df[df['age']> 40]
df.head(5)

,employee_id,name,department,age,salary,city,gender,designation,experience_years
0,1,Simran,IT,44,109723,Pune,Female,Manager,12
1,2,Priya,Marketing,35,119406,Bangalore,Male,Analyst,2
2,3,Simran,HR,50,37769,Chandigarh,Female,Analyst,19
3,4,Arjun,Marketing,37,26682,Delhi,Male,Manager,0
4,5,Karan,HR,34,44816,Delhi,Female,Team Lead,26

In [5]:
df.sort_values(by='salary', ascending=False)
df.head(5)

,employee_id,name,department,age,salary,city,gender,designation,experience_years
0,1,Simran,IT,44,109723,Pune,Female,Manager,12
1,2,Priya,Marketing,35,119406,Bangalore,Male,Analyst,2
2,3,Simran,HR,50,37769,Chandigarh,Female,Analyst,19
3,4,Arjun,Marketing,37,26682,Delhi,Male,Manager,0
4,5,Karan,HR,34,44816,Delhi,Female,Team Lead,26

In [6]:
df.sort_values(by=["salary", "name"], ascending=[False, True])
df.head(5)

,employee_id,name,department,age,salary,city,gender,designation,experience_years
0,1,Simran,IT,44,109723,Pune,Female,Manager,12
1,2,Priya,Marketing,35,119406,Bangalore,Male,Analyst,2
2,3,Simran,HR,50,37769,Chandigarh,Female,Analyst,19
3,4,Arjun,Marketing,37,26682,Delhi,Male,Manager,0
4,5,Karan,HR,34,44816,Delhi,Female,Team Lead,26

In [7]:
df.groupby('department').count()
df.head(5)

,employee_id,name,department,age,salary,city,gender,designation,experience_years
0,1,Simran,IT,44,109723,Pune,Female,Manager,12
1,2,Priya,Marketing,35,119406,Bangalore,Male,Analyst,2
2,3,Simran,HR,50,37769,Chandigarh,Female,Analyst,19
3,4,Arjun,Marketing,37,26682,Delhi,Male,Manager,0
4,5,Karan,HR,34,44816,Delhi,Female,Team Lead,26

In [8]:
df.head(5)

,employee_id,name,department,age,salary,city,gender,designation,experience_years
0,1,Simran,IT,44,109723,Pune,Female,Manager,12
1,2,Priya,Marketing,35,119406,Bangalore,Male,Analyst,2
2,3,Simran,HR,50,37769,Chandigarh,Female,Analyst,19
3,4,Arjun,Marketing,37,26682,Delhi,Male,Manager,0
4,5,Karan,HR,34,44816,Delhi,Female,Team Lead,26

In [9]:
df.shape

(500, 9)

In [10]:
df.isnull()
df.isnull().sum()

employee_id         0
name                0
department          0
age                 0
salary              0
city                0
gender              0
designation         0
experience_years    0
dtype: int64

In [11]:
df.dropna()
df.head(5)

,employee_id,name,department,age,salary,city,gender,designation,experience_years
0,1,Simran,IT,44,109723,Pune,Female,Manager,12
1,2,Priya,Marketing,35,119406,Bangalore,Male,Analyst,2
2,3,Simran,HR,50,37769,Chandigarh,Female,Analyst,19
3,4,Arjun,Marketing,37,26682,Delhi,Male,Manager,0
4,5,Karan,HR,34,44816,Delhi,Female,Team Lead,26

In [12]:
df.fillna({"salary": 1000000}, inplace=False)
df.head(5)

,employee_id,name,department,age,salary,city,gender,designation,experience_years
0,1,Simran,IT,44,109723,Pune,Female,Manager,12
1,2,Priya,Marketing,35,119406,Bangalore,Male,Analyst,2
2,3,Simran,HR,50,37769,Chandigarh,Female,Analyst,19
3,4,Arjun,Marketing,37,26682,Delhi,Male,Manager,0
4,5,Karan,HR,34,44816,Delhi,Female,Team Lead,26

In [13]:
df["name"]
df.head(5)

,employee_id,name,department,age,salary,city,gender,designation,experience_years
0,1,Simran,IT,44,109723,Pune,Female,Manager,12
1,2,Priya,Marketing,35,119406,Bangalore,Male,Analyst,2
2,3,Simran,HR,50,37769,Chandigarh,Female,Analyst,19
3,4,Arjun,Marketing,37,26682,Delhi,Male,Manager,0
4,5,Karan,HR,34,44816,Delhi,Female,Team Lead,26

In [14]:
data = {
    "EmployeeID": [101, 102, 103, 104, 105],
    "Name": ["Amit", "Neha", "Rahul", "Priya", "Karan"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Age": [25, 30, 35, 28, 40],
    "Salary": [45000, 55000, 60000, 52000, None]
}

df1 = pd.DataFrame(data)

In [15]:
df1.head(3)

   EmployeeID   Name Department  Age   Salary
0         101   Amit         IT   25  45000.0
1         102   Neha         HR   30  55000.0
2         103  Rahul         IT   35  60000.0

In [16]:
df1["Salary"].mean()

np.float64(53000.0)

In [17]:
df1[df1["Salary"] > 50000]

   EmployeeID   Name Department  Age   Salary
1         102   Neha         HR   30  55000.0
2         103  Rahul         IT   35  60000.0
3         104  Priya    Finance   28  52000.0

In [18]:
df1.sort_values(by="Age")

   EmployeeID   Name Department  Age   Salary
0         101   Amit         IT   25  45000.0
3         104  Priya    Finance   28  52000.0
1         102   Neha         HR   30  55000.0
2         103  Rahul         IT   35  60000.0
4         105  Karan         HR   40      NaN

In [19]:
df1.groupby("Department")["Salary"].sum()

Department
Finance     52000.0
HR          55000.0
IT         105000.0
Name: Salary, dtype: float64

In [20]:
df1["Bonus"] = df1["Salary"] * 0.10
df1

   EmployeeID   Name Department  Age   Salary   Bonus
0         101   Amit         IT   25  45000.0  4500.0
1         102   Neha         HR   30  55000.0  5500.0
2         103  Rahul         IT   35  60000.0  6000.0
3         104  Priya    Finance   28  52000.0  5200.0
4         105  Karan         HR   40      NaN     NaN

In [21]:
df1["Salary"] = df1["Salary"].fillna(df1["Salary"].mean())
df1

   EmployeeID   Name Department  Age   Salary   Bonus
0         101   Amit         IT   25  45000.0  4500.0
1         102   Neha         HR   30  55000.0  5500.0
2         103  Rahul         IT   35  60000.0  6000.0
3         104  Priya    Finance   28  52000.0  5200.0
4         105  Karan         HR   40  53000.0     NaN

In [22]:
df1.rename(columns={"EmployeeID": "ID"}, inplace=True)
df1

    ID   Name Department  Age   Salary   Bonus
0  101   Amit         IT   25  45000.0  4500.0
1  102   Neha         HR   30  55000.0  5500.0
2  103  Rahul         IT   35  60000.0  6000.0
3  104  Priya    Finance   28  52000.0  5200.0
4  105  Karan         HR   40  53000.0     NaN