In [ ]:
import pandas as pd
# load your uploaded file
df = pd.read_csv("/content/iris.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [ ]:
print("Shape:", df.shape)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Shape: (150, 5)
Rows: 150
Columns: 5

In [ ]:
numerical_cols = df.select_dtypes(include=['int64','float64']).columns
categorical_cols = df.select_dtypes(include=['object','category']).columns
print("Numerical columns:", list(numerical_cols))
print("Categorical columns:", list(categorical_cols))

Numerical columns: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
Categorical columns: ['species']

In [ ]:
stats = df[numerical_cols].agg(['mean','median','std'])
stats

        sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
std         0.828066     0.433594      1.764420     0.763161

In [ ]:
std_values = df[numerical_cols].std()
highest_variability_col = std_values.idxmax()

print("Standard deviation:\n", std_values)
print("\nColumn with highest variability:", highest_variability_col)
print(f"\nJustification: {highest_variability_col} has highest variability because it has the largest standard deviation.")

Standard deviation:
 sepal_length    0.828066
sepal_width     0.433594
petal_length    1.764420
petal_width     0.763161
dtype: float64

Column with highest variability: petal_length

Justification: petal_length has highest variability because it has the largest standard deviation.

In [ ]:
missing_values = df.isnull().sum()
missing_values

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64